services:
  backend-1:
    build: ./net-todo-fastendpoints
    ports:
      - "5030:5030"
  backend-2:
    build: ./net-todo-fastendpoints
    ports:
      - "5031:5030"

  frontend:
    build: ./client-todo-fastendpoints
    ports:
      - "8000:80"

  redis:
    image: redis:8-alpine
    ports:
      - 6379:6379
